### ISSUE TITLE
Schreibform

### ISSUE THREAD

**Issue by nicoausnrw** [ehmkah/lesbar#3]
Nachdem ich über diesen [tweet](https://twitter.com/ennopark/status/1101525758755905541) gestolpert bin, habe ich nach einer Lösung gesucht und war recht glücklich diese zu finden. Leider erkennt das Addon noch nicht diese Schreibform: Platzhalter:innen.

**Comment by ehmkah** [comment]
Vielen Dank für den Hinweis. Ich habe es mal als Testfall aufgenommen. Leider habe ich bisher die Fälle alle redundant gebaut - ich muss das mal zusammenfassen.

**Comment by hello-world-dot-c** [comment]
Ist das immernoch ein Problem? Habe gerade eine Webseite mit Benutzer:innen vor mir, mit dem Add-on aktiv.

**Comment by ehmkah** [comment]
Guter Punkt scheint zu funktionieren. ich schliesse das Ticket mal .

Danke.
