### ISSUE TITLE
geht nicht

### ISSUE THREAD

**Issue by imperatom** [ehmkah/lesbar#6]
Die Idee ist ja tatsächlich sehr nett. Leider funktioniert die App offenbar nicht so ohne weiteres. Ich habe in meinen Firefox zwei Webseiten getestet und bei beiden bleiben lauter *innen sichtbar:

http://www.buurtzorg-in-deutschland.org/buurtzorg/

https://www.gew-hamburg.de/themen/aktionen-und-kampagnen/mietenmove-2019-mietenwahnsinn-stoppen-guenstige-raeume-fuer-alle

**Comment by ehmkah** [comment]
Die Ersetzung findet nicht automatisch statt. Du müsstest nachdem die Seite geladen wurde auf das Addon-Icon (Deutschlandfahne) klicken. Ich wollte, dass Seiten nur bei Bedarf übersetzt werden. 

Alternativ kannst Du auch http://binnenibegone.awardspace.com/ ausprobieren, da findet das ersetzen automatisch statt.

**Comment by imperatom** [comment]
> Alternativ kannst Du auch http://binnenibegone.awardspace.com/ ausprobieren, da findet das ersetzen automatisch statt.

Das klappt prima, danke für den Tipp!
