### ISSUE TITLE
Funktioniert nicht auf aldi-sued.de

### ISSUE THREAD

**Issue by navid-zamani** [ehmkah/lesbar#8]
Hallo,

ich hab grad bemerkt, daß die Erweiterung auf

https://www.aldi-sued.de/de/hilfe-und-kontakt.html

ihren Dienst nicht tut. Das geht natürlich garnicht.

Oh, und generell: Danke für die Erweiterung!

— Ein Nutzer (Außen) 😆

**Comment by ehmkah** [comment]
Hab mal auf die Seite geschaut. Für mich sieht es so aus als binden sie Bilder ein. Texte in Bildern ersetzen, wäre natürlich auch spannend, aber ich glaube ausserhalb meiner Möglichkeiten ;-)

Hast Du die anderen Plugins mal ausprobiert, die es im google/firefox store gibt? Vielleicht funktionieren die auch für Bilder.

**Comment by navid-zamani** [comment]
Ok, das ist natürlich eine Ebene technischer Inkompetenz, gegen die du nichts mehr ausrichten kannst. :D  
Ich hätt selber sehen können, daß das nur Bilder sind. Aber offen gesagt war das für mich als ehemaligen Webentwickler so absurd, daß es mir nicht ins Hirn kam. :))

Keins der Plugins was das könnte, würde die Texterkennung lokal ausführen. Das zieht immer noch einfach zu viele Ressourcen.  
Ich weiß daß Google und Konsorten natürlich Texte in Bildern erkennen können, und Dienste dafür bieten. Aber das hieße ja alles an die Datenkrake senden, und das will ja auch keiner. :D  

Trotzdem Danke fürs Nachschauen. :)

**Comment by navid-zamani** [comment]
P.S.: Ich hab mal geschaut, weil ich dachte vielleicht ist es ein SVG … Nein, es ist nicht nur ein Bild. Es ist auch noch ein JPEG!! Man kann die Artefakte um die Buchstaben sehen! Wow! Da hätte ich aber damals direkt zum Chef müssen, wenn rausgekommen wäre daß ich so nen Mist code. ;)
